# Generated by Django 3.2.5 on 2021-08-02 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210802_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 2, 12, 10, 17, 105459)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 2, 12, 10, 17, 105504)),
        ),
    ]
